### ISSUE TITLE
How to use library for Android studio?

### ISSUE THREAD

**Issue by AndroidLTG** [ragnraok/android-image-filter#19]
Hi. I use android studio but i can't use your's library. How to use it ?

**Comment by Vierco** [comment]
@ragnraok Thank you for sharing your work.
I would also like to use it on android studio , can you explain how?

**Comment by anilsangani** [comment]
@ragnraok i am alos facing problem while using it in Android Studio so please can you assist on that

**Comment by ragnraok** [comment]
The official support for android NDK gradle plugin still in experiment status: http://tools.android.com/tech-docs/new-build-system/gradle-experimental, I created a branch called gradle-ndk which used this plugin to build this project, but it seem than current version is not well support for multi modules dependencies,
so I will use the current version of gradle plugin to rebuild the project, since now is in the Chinese new year, so I may do it in the next few days :)

**Comment by rohitdhall07** [comment]
Hi,
Any update for using it in Android Studio?
I've tried everything possible (updating to new experimentalgradle). Still getting cn.Ragnraok package not found after adding this lib as dependency in demo module.

Can you please help about this problem?

**Comment by altaf2892** [comment]
yeah same problem how to use it in Android studio?

**Comment by ragnraok** [comment]
I have refactored this, please checkout the new version
